In [52]:
import numpy as np
import pandas as pd
import json
 
# Opening JSON file
f = open('human.json')
 
# returns JSON object as 
# a dictionary
data = json.load(f)
# data = data["results"]['1705603200893']

stimuli = json.load(open('stimuli.json'))

df_joint = pd.read_csv("results_joint.csv")
df_belief = pd.read_csv("results_belief.csv")
df_goal = pd.read_csv("results_goal.csv")

In [10]:
len(data["results"]['1705958507527'].keys())

14

In [40]:
def extract_steps(metadata, idx):
    for dic in metadata:
        if dic["name"] == idx:
            return dic["times"]

In [43]:
extract_steps(stimuli, "1_1")

[1, 4, 6]

In [8]:
df.head()

,plan_id,true_goal,act_temperature,timestep,is_judgment,action,goal_probs_1,goal_probs_2,goal_probs_3,goal_probs_4,...,state_probs_12,state_probs_13,state_probs_14,state_probs_15,state_probs_16,state_probs_17,state_probs_18,n_statements,statement_probs_1,statement_probs_2
0,1_1,4,"(Gen.InverseGamma(), (0.5, 1.0), 2, -3.0:0.25:...",0,False,(--),0.250000,0.250000,0.250000,0.250000,...,0.055556,0.055556,0.055556,0.055556,0.055556,0.055556,0.055556,2,0.111111,0.888889
1,1_1,4,"(Gen.InverseGamma(), (0.5, 1.0), 2, -3.0:0.25:...",1,False,(right human),0.049324,0.293625,0.363425,0.293625,...,0.063311,0.063311,0.051678,0.051678,0.063311,0.063311,0.051678,2,0.103356,0.896644
2,1_1,4,"(Gen.InverseGamma(), (0.5, 1.0), 2, -3.0:0.25:...",2,False,(right human),0.015397,0.294624,0.395356,0.294624,...,0.066748,0.066748,0.049959,0.049959,0.066748,0.066748,0.049959,2,0.099919,0.900081
3,1_1,4,"(Gen.InverseGamma(), (0.5, 1.0), 2, -3.0:0.25:...",3,True,(down human),0.007248,0.468529,0.055694,0.468529,...,0.078166,0.078166,0.044250,0.044250,0.078166,0.078166,0.044250,2,0.088500,0.911500
4,1_1,4,"(Gen.InverseGamma(), (0.5, 1.0), 2, -3.0:0.25:...",4,False,(down human),0.002909,0.492060,0.012971,0.492060,...,0.080930,0.080930,0.042868,0.042868,0.080930,0.080930,0.042868,2,0.085736,0.914264

In [74]:
extract_steps(stimuli, "9_2")

[1, 6, 8]

In [100]:
human = pd.DataFrame(columns=["plan_id","timestep", "statement_probs_1","statement_probs_2"])

In [26]:

rating = []
p_id = []

statement_1 = []
statement_2 = []
for uid, entry in data["results"].items():
    if len(entry.keys()) == 14:
        
        r_1 = {}
        r_2 = {}
        
        for idx, problem in entry.items():
        #     print(idx)
            if idx not in ["exam", "stimuli_set", "total_payment","total_reward","user_id"]:
                p_id.append(idx)
                r_1[idx] = []
                r_2[idx] = []
                for t, step in problem.items():
                    if t!="reward":
                        r_1[idx].append(step['statement_ratings'][0])
                        r_2[idx].append(step['statement_ratings'][1])
#         #             print(step)
#                     if t!="reward":
#                         rating.extend(step['statement_ratings'])
#         #                 print(extract_steps(stimuli, idx), t, step['statement_ratings'])
#                         new_row =pd.DataFrame({"plan_id":idx, "timestep":extract_steps(stimuli, idx)[1:][int(t)]-1,
#                                                   "statement_probs_1": step['statement_ratings'][0],
#                                                   "statement_probs_2": step['statement_ratings'][1],

#                                              }, index=[0])
#                         print(new_row)
#                         human = pd.concat([human, new_row], axis=0, ignore_index=True)
#                 human = human.append()
        statement_1.append(r_1)
        statement_2.append(r_2)

In [27]:
statement_1

[{'1_1': [4, 1],
  '2_2': [4],
  '3_1': [4, 4],
  '4_2': [4, 1],
  '5_2': [4, 4, 1],
  '6_2': [4, 1, 1],
  '7_2': [4, 1],
  '8_2': [4, 1],
  '9_2': [4, 4]},
 {'1_2': [4, 1],
  '1_3': [1, 1, 1],
  '2_1': [7, 7],
  '4_1': [3, 1],
  '5_1': [1, 1],
  '6_1': [1, 7],
  '7_1': [1, 1],
  '8_1': [7, 4, 1],
  '9_1': [6, 7]},
 {'1_1': [4, 1],
  '1_3': [4, 1, 1],
  '2_2': [5],
  '4_2': [4, 3],
  '5_2': [5, 1, 1],
  '6_2': [4, 1, 1],
  '7_2': [4, 1],
  '8_2': [5, 1],
  '9_2': [4, 4]},
 {'1_2': [6, 1],
  '2_1': [5, 7],
  '3_1': [6, 1],
  '4_1': [6, 1],
  '5_1': [2, 1],
  '6_1': [4, 7],
  '7_1': [1, 1],
  '8_1': [1, 7, 7],
  '9_1': [6, 7]},
 {'1_1': [4, 1],
  '1_3': [4, 1, 1],
  '2_1': [4, 7],
  '4_2': [4, 1],
  '5_2': [4, 4, 2],
  '6_2': [4, 3, 1],
  '7_2': [5, 1],
  '8_2': [4, 1],
  '9_2': [3, 4]},
 {'1_2': [5, 1],
  '2_2': [1],
  '3_1': [4, 1],
  '4_1': [5, 1],
  '5_1': [1, 1],
  '6_1': [4, 7],
  '7_1': [1, 1],
  '8_1': [3, 1, 7],
  '9_1': [7, 7]},
 {'1_1': [1, 1],
  '1_3': [6, 1, 1],
  '2_1': [1, 7],
  '4_1': [7, 7],
  '5_2': [7, 7, 1],
  '6_2': [7, 1, 1],
  '7_2': [7, 1],
  '8_2': [7, 1],
  '9_2': [2, 7]},
 {'1_2': [4, 1],
  '2_2': [1],
  '3_1': [4, 1],
  '4_2': [4, 1],
  '5_1': [1, 1],
  '6_1': [4, 7],
  '7_1': [1, 1],
  '8_1': [1, 6, 7],
  '9_1': [4, 6]},
 {'1_1': [4, 1],
  '1_3': [4, 1, 1],
  '2_1': [4, 7],
  '4_1': [4, 1],
  '5_1': [3, 1],
  '6_2': [4, 1, 1],
  '7_2': [2, 1],
  '8_2': [4, 1],
  '9_2': [4, 4]},
 {'1_2': [3, 4],
  '2_2': [3],
  '3_1': [7, 2],
  '4_2': [4, 4],
  '5_2': [4, 4, 3],
  '6_1': [4, 4],
  '7_1': [4, 4],
  '8_1': [4, 4, 7],
  '9_1': [4, 7]},
 {'1_1': [1, 1],
  '1_3': [5, 1, 1],
  '2_1': [7, 7],
  '4_1': [4, 1],
  '5_1': [1, 1],
  '6_1': [7, 7],
  '7_1': [1, 1],
  '8_2': [1, 1],
  '9_2': [4, 7]}]

In [32]:
final_rating_1 = {}
final_rating_2 = {}

for idx in p_id:
    temp_list_1 = []
    temp_list_2 = []
    for dic in statement_1:
        if idx in dic.keys():
            temp_list_1.append(dic[idx])
    for dic in statement_1:
        if idx in dic.keys():
            temp_list_2.append(dic[idx])
    final_rating_1[idx] = np.array(temp_list_1).mean(0)
    final_rating_2[idx] = np.array(temp_list_2).mean(0)

In [33]:
final_rating_1

{'1_1': array([3., 1.]),
 '2_2': array([2.8]),
 '3_1': array([5. , 1.8]),
 '4_2': array([4., 2.]),
 '5_2': array([4.8, 4. , 1.6]),
 '6_2': array([4.6, 1.4, 1. ]),
 '7_2': array([4.4, 1. ]),
 '8_2': array([4.16666667, 1.        ]),
 '9_2': array([3.5, 5. ]),
 '1_2': array([4.4, 1.6]),
 '1_3': array([4., 1., 1.]),
 '2_1': array([4.66666667, 7.        ]),
 '4_1': array([4.83333333, 2.        ]),
 '5_1': array([1.5, 1. ]),
 '6_1': array([4. , 6.5]),
 '7_1': array([1.5, 1.5]),
 '8_1': array([3.2, 4.4, 5.8]),
 '9_1': array([5.4, 6.8])}

In [36]:
human = pd.read_csv("human.csv")

In [62]:
p_id.append("9_2")

In [63]:
p_id

['1_1',
 '2_2',
 '3_1',
 '4_2',
 '5_2',
 '6_2',
 '7_2',
 '8_2',
 '9_2',
 '1_2',
 '1_3',
 '2_1',
 '4_1',
 '5_1',
 '6_1',
 '7_1',
 '8_1',
 '9_1',
 '9_2']

In [64]:
arr = []
for idx in p_id:
    print(idx)
    arr.extend(final_rating_1[idx])
    arr.extend(final_rating_2[idx])

1_1
2_2
3_1
4_2
5_2
6_2
7_2
8_2
9_2
1_2
1_3
2_1
4_1
5_1
6_1
7_1
8_1
9_1
9_2

In [38]:
arr

[3.0,
 1.0,
 3.0,
 1.0,
 2.8,
 2.8,
 5.0,
 1.8,
 5.0,
 1.8,
 4.0,
 2.0,
 4.0,
 2.0,
 4.8,
 4.0,
 1.6,
 4.8,
 4.0,
 1.6,
 4.6,
 1.4,
 1.0,
 4.6,
 1.4,
 1.0,
 4.4,
 1.0,
 4.4,
 1.0,
 4.166666666666667,
 1.0,
 4.166666666666667,
 1.0,
 3.5,
 5.0,
 3.5,
 5.0,
 4.4,
 1.6,
 4.4,
 1.6,
 4.0,
 1.0,
 1.0,
 4.0,
 1.0,
 1.0,
 4.666666666666667,
 7.0,
 4.666666666666667,
 7.0,
 4.833333333333333,
 2.0,
 4.833333333333333,
 2.0,
 1.5,
 1.0,
 1.5,
 1.0,
 4.0,
 6.5,
 4.0,
 6.5,
 1.5,
 1.5,
 1.5,
 1.5,
 3.2,
 4.4,
 5.8,
 3.2,
 4.4,
 5.8,
 5.4,
 6.8,
 5.4,
 6.8,
 3.0,
 1.0,
 3.0,
 1.0,
 4.0,
 1.0,
 1.0,
 4.0,
 1.0,
 1.0,
 2.8,
 2.8,
 4.0,
 2.0,
 4.0,
 2.0,
 4.8,
 4.0,
 1.6,
 4.8,
 4.0,
 1.6,
 4.6,
 1.4,
 1.0,
 4.6,
 1.4,
 1.0,
 4.4,
 1.0,
 4.4,
 1.0,
 4.166666666666667,
 1.0,
 4.166666666666667,
 1.0,
 3.5,
 5.0,
 3.5,
 5.0,
 4.4,
 1.6,
 4.4,
 1.6,
 4.666666666666667,
 7.0,
 4.666666666666667,
 7.0,
 5.0,
 1.8,
 5.0,
 1.8,
 4.833333333333333,
 2.0,
 4.833333333333333,
 2.0,
 1.5,
 1.0,
 1.5,
 1.0,
 4.0,
 6.5,
 4.0,
 6.5,
 1.5,
 1.5,
 1.5,
 1.5,
 3.2,
 4.4,
 5.8,
 3.2,
 4.4,
 5.8,
 5.4,
 6.8,
 5.4,
 6.8,
 3.0,
 1.0,
 3.0,
 1.0,
 4.0,
 1.0,
 1.0,
 4.0,
 1.0,
 1.0,
 4.666666666666667,
 7.0,
 4.666666666666667,
 7.0,
 4.0,
 2.0,
 4.0,
 2.0,
 4.8,
 4.0,
 1.6,
 4.8,
 4.0,
 1.6,
 4.6,
 1.4,
 1.0,
 4.6,
 1.4,
 1.0,
 4.4,
 1.0,
 4.4,
 1.0,
 4.166666666666667,
 1.0,
 4.166666666666667,
 1.0,
 3.5,
 5.0,
 3.5,
 5.0,
 4.4,
 1.6,
 4.4,
 1.6,
 2.8,
 2.8,
 5.0,
 1.8,
 5.0,
 1.8,
 4.833333333333333,
 2.0,
 4.833333333333333,
 2.0,
 1.5,
 1.0,
 1.5,
 1.0,
 4.0,
 6.5,
 4.0,
 6.5,
 1.5,
 1.5,
 1.5,
 1.5,
 3.2,
 4.4,
 5.8,
 3.2,
 4.4,
 5.8,
 5.4,
 6.8,
 5.4,
 6.8,
 3.0,
 1.0,
 3.0,
 1.0,
 4.0,
 1.0,
 1.0,
 4.0,
 1.0,
 1.0,
 4.666666666666667,
 7.0,
 4.666666666666667,
 7.0,
 4.833333333333333,
 2.0,
 4.833333333333333,
 2.0,
 4.8,
 4.0,
 1.6,
 4.8,
 4.0,
 1.6,
 4.6,
 1.4,
 1.0,
 4.6,
 1.4,
 1.0,
 4.4,
 1.0,
 4.4,
 1.0,
 4.166666666666667,
 1.0,
 4.166666666666667,
 1.0,
 3.5,
 5.0,
 3.5,
 5.0,
 4.4,
 1.6,
 4.4,
 1.6,
 2.8,
 2.8,
 5.0,
 1.8,
 5.0,
 1.8,
 4.0,
 2.0,
 4.0,
 2.0,
 1.5,
 1.0,
 1.5,
 1.0,
 4.0,
 6.5,
 4.0,
 6.5,
 1.5,
 1.5,
 1.5,
 1.5,
 3.2,
 4.4,
 5.8,
 3.2,
 4.4,
 5.8,
 5.4,
 6.8,
 5.4,
 6.8,
 3.0,
 1.0,
 3.0,
 1.0,
 4.0,
 1.0,
 1.0,
 4.0,
 1.0,
 1.0,
 4.666666666666667,
 7.0,
 4.666666666666667,
 7.0,
 4.833333333333333,
 2.0,
 4.833333333333333,
 2.0,
 1.5,
 1.0,
 1.5,
 1.0,
 4.6,
 1.4,
 1.0,
 4.6,
 1.4,
 1.0,
 4.4,
 1.0,
 4.4,
 1.0,
 4.166666666666667,
 1.0,
 4.166666666666667,
 1.0,
 3.5,
 5.0,
 3.5,
 5.0,
 4.4,
 1.6,
 4.4,
 1.6,
 2.8,
 2.8,
 5.0,
 1.8,
 5.0,
 1.8,
 4.0,
 2.0,
 4.0,
 2.0,
 4.8,
 4.0,
 1.6,
 4.8,
 4.0,
 1.6,
 4.0,
 6.5,
 4.0,
 6.5,
 1.5,
 1.5,
 1.5,
 1.5,
 3.2,
 4.4,
 5.8,
 3.2,
 4.4,
 5.8,
 5.4,
 6.8,
 5.4,
 6.8,
 3.0,
 1.0,
 3.0,
 1.0,
 4.0,
 1.0,
 1.0,
 4.0,
 1.0,
 1.0,
 4.666666666666667,
 7.0,
 4.666666666666667,
 7.0,
 4.833333333333333,
 2.0,
 4.833333333333333,
 2.0,
 1.5,
 1.0,
 1.5,
 1.0,
 4.0,
 6.5,
 4.0,
 6.5,
 1.5,
 1.5,
 1.5,
 1.5,
 4.166666666666667,
 1.0,
 4.166666666666667,
 1.0,
 3.5,
 5.0,
 3.5,
 5.0]

In [103]:
human.to_csv("human.csv", index=False)

In [24]:
p_id = pd.read_csv("human.csv")["plan_id"].values

In [28]:
pd.read_csv("human.csv")

   plan_id  timestep  statement_probs_1  statement_probs_2
0      1_1         3                  3                  5
1      1_1         5                  1                  7
2      1_3        15                  4                  4
3      1_3        18                  2                  5
4      1_3        20                  1                  7
5      2_1         4                  4                  4
6      2_1         9                  6                  2
7      4_1         5                  4                  4
8      4_1         8                  1                  1
9      5_2         2                  4                  4
10     5_2         9                  4                  4
11     5_2        13                  1                  7
12     6_2         4                  4                  4
13     6_2         8                  1                  4
14     6_2        14                  1                  1
15     7_2         2                  4                  4
16     7_2         6                  2                  7
17     8_2         4                  4                  4
18     8_2         7                  2                  6
19     9_2         5                  4                  4
20     9_2         7                  4                  4

In [69]:
model_rating = []
df = df_joint
for idx in p_id:
    for t in extract_steps(stimuli, idx)[1:]:
        print(idx, t)
        model_rating.append(df[(df["plan_id"]==idx) &(df["timestep"]==t-1) ]["statement_probs_1"].values[0])
        model_rating.append(df[(df["plan_id"]==idx) &(df["timestep"]==t-1) ]["statement_probs_2"].values[0])

1_1 4
1_1 6
2_2 6
3_1 4
3_1 6
4_2 6
4_2 9
5_2 3
5_2 10
5_2 14
6_2 5
6_2 9
6_2 15
7_2 3
7_2 7
8_2 5
8_2 8
9_2 6
9_2 8
1_2 17
1_2 20
1_3 16
1_3 19
1_3 21
2_1 5
2_1 10
4_1 6
4_1 9
5_1 4
5_1 8
6_1 3
6_1 7
7_1 4
7_1 7
8_1 8
8_1 18
8_1 25
9_1 3
9_1 9
9_2 6
9_2 8

In [71]:
np.corrcoef(model_rating, arr)

array([[ 1.        , -0.07943631],
       [-0.07943631,  1.        ]])

In [67]:
len(model_rating)

428

In [68]:
len(arr)

82